name: Go Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
            target: darwin-arm64
          - os: ubuntu-latest
            target: linux-amd64
          - os: windows-latest
            target: windows-amd64

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Build
      run: |
        go build -o main -v ./main.go

    - name: Zip Artifact
      if: matrix.os == 'windows-latest'
      run: |
        7z a ${{ matrix.target }}.zip main
    - name: Zip Artifact
      if: matrix.os != 'windows-latest'
      run: |
        zip ${{ matrix.target }}.zip main

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.target }}
        path: ${{ matrix.target }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create Tag
      id: create_tag
      uses: anothrNick/github-tag-action@1.35.0
      env:
        DEFAULT_BUMP: patch
        WITH_V: true
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.create_tag.outputs.new_tag }}
        release_name: Release ${{ steps.create_tag.outputs.new_tag }}
        draft: false
        prerelease: false

    - name: Download Artifacts
      uses: actions/download-artifact@v3

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./darwin-arm64/darwin-arm64.zip
        asset_name: darwin-arm64.zip
        asset_content_type: application/zip

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./linux-amd64/linux-amd64.zip
        asset_name: linux-amd64.zip
        asset_content_type: application/zip

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./windows-amd64/windows-amd64.zip
        asset_name: windows-amd64.zip
        asset_content_type: application/zip
